import "../styles/globals.css";
import type { AppProps } from "next/app";
import React from "react";
import Head from "next/head";
import { QueryClient, QueryClientProvider } from "react-query";

function MyApp({ Component, pageProps }: AppProps) {
  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <title>WTX - Tech challenge</title>
        <meta name="description" content="Generated by WTX team" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <header />
      <main>
        <Component {...pageProps} />
      </main>
      <footer>
        <a href="https://wtx.com" target="_blank" rel="noopener noreferrer">
          Powered by WTX
        </a>
      </footer>
    </QueryClientProvider>
  );
}

export default MyApp;
